module.exports = {
  play: "play",
  message: "message",
  disconnect: "disconnect",
  notification: "notification",
  callPeer: "callPeer",
  endCall: "endCall",
  callEnded: "callEnded",
  opponentIsCalling: "opponentIsCalling",
  rejectCall: "rejectCall",
  callRejected: "callRejected",
  answerCall: "answerCall",
  callAnswered: "callAnswered",
  isOpponentConnected: "isOpponentConnected",
};
